name: Crawler Runner

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with: { ref: master }
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Crawler
      run: |
        python NeedFree.py
    - name: Update free details json
      run: |
        git pull
        git config --global user.name "LexKreyn"
        git config --global user.email "czaralex01@gmail.com"
        git commit -am "Automated update json"
        git push
